#ifdef X
X(MOUSE_M_UP)
X(MOUSE_M_DOWN)
X(MOUSE_M_LEFT)
X(MOUSE_M_RIGHT)
X(MOUSE_BTN1)
X(MOUSE_BTN2)
X(MOUSE_BTN3)
X(MOUSE_SCROLL_UP)
X(MOUSE_SCROLL_DOWN)
X(MOUSE_SCROLL_LEFT)
X(MOUSE_SCROLL_RIGHT)
#endif
